// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`           // game-server 实例标识
	LastVersion   uint64                 `protobuf:"varint,2,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"` // 可选：断线重连时告诉服务端已处理版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SubscribeRequest) GetLastVersion() uint64 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

type PoolConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PoolId               uint32                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	SRankBaseRate        float64                `protobuf:"fixed64,2,opt,name=s_rank_base_rate,json=sRankBaseRate,proto3" json:"s_rank_base_rate,omitempty"`
	ARankBaseRate        float64                `protobuf:"fixed64,3,opt,name=a_rank_base_rate,json=aRankBaseRate,proto3" json:"a_rank_base_rate,omitempty"`
	AGuaranteeInterval   int32                  `protobuf:"varint,4,opt,name=a_guarantee_interval,json=aGuaranteeInterval,proto3" json:"a_guarantee_interval,omitempty"`
	SPityStart           int32                  `protobuf:"varint,5,opt,name=s_pity_start,json=sPityStart,proto3" json:"s_pity_start,omitempty"`
	SPityStep            float64                `protobuf:"fixed64,6,opt,name=s_pity_step,json=sPityStep,proto3" json:"s_pity_step,omitempty"`
	SPityEnd             int32                  `protobuf:"varint,7,opt,name=s_pity_end,json=sPityEnd,proto3" json:"s_pity_end,omitempty"`
	LimitPity            int32                  `protobuf:"varint,8,opt,name=limit_pity,json=limitPity,proto3" json:"limit_pity,omitempty"`
	LimitRateWhenS       float64                `protobuf:"fixed64,9,opt,name=limit_rate_when_s,json=limitRateWhenS,proto3" json:"limit_rate_when_s,omitempty"`
	MaxLimitedCharacters int32                  `protobuf:"varint,10,opt,name=max_limited_characters,json=maxLimitedCharacters,proto3" json:"max_limited_characters,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PoolConfig) Reset() {
	*x = PoolConfig{}
	mi := &file_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolConfig) ProtoMessage() {}

func (x *PoolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolConfig.ProtoReflect.Descriptor instead.
func (*PoolConfig) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{1}
}

func (x *PoolConfig) GetPoolId() uint32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *PoolConfig) GetSRankBaseRate() float64 {
	if x != nil {
		return x.SRankBaseRate
	}
	return 0
}

func (x *PoolConfig) GetARankBaseRate() float64 {
	if x != nil {
		return x.ARankBaseRate
	}
	return 0
}

func (x *PoolConfig) GetAGuaranteeInterval() int32 {
	if x != nil {
		return x.AGuaranteeInterval
	}
	return 0
}

func (x *PoolConfig) GetSPityStart() int32 {
	if x != nil {
		return x.SPityStart
	}
	return 0
}

func (x *PoolConfig) GetSPityStep() float64 {
	if x != nil {
		return x.SPityStep
	}
	return 0
}

func (x *PoolConfig) GetSPityEnd() int32 {
	if x != nil {
		return x.SPityEnd
	}
	return 0
}

func (x *PoolConfig) GetLimitPity() int32 {
	if x != nil {
		return x.LimitPity
	}
	return 0
}

func (x *PoolConfig) GetLimitRateWhenS() float64 {
	if x != nil {
		return x.LimitRateWhenS
	}
	return 0
}

func (x *PoolConfig) GetMaxLimitedCharacters() int32 {
	if x != nil {
		return x.MaxLimitedCharacters
	}
	return 0
}

type ConfigUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // 单调递增版本号
	UpdatedAtUnixMs int64                  `protobuf:"varint,2,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	Config          *PoolConfig            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigUpdate) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *ConfigUpdate) GetConfig() *PoolConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_proto_config_proto protoreflect.FileDescriptor

const file_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x12proto/config.proto\x12\rconfigsync.v1\"R\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12!\n" +
	"\flast_version\x18\x02 \x01(\x04R\vlastVersion\"\x89\x03\n" +
	"\n" +
	"PoolConfig\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\rR\x06poolId\x12'\n" +
	"\x10s_rank_base_rate\x18\x02 \x01(\x01R\rsRankBaseRate\x12'\n" +
	"\x10a_rank_base_rate\x18\x03 \x01(\x01R\raRankBaseRate\x120\n" +
	"\x14a_guarantee_interval\x18\x04 \x01(\x05R\x12aGuaranteeInterval\x12 \n" +
	"\fs_pity_start\x18\x05 \x01(\x05R\n" +
	"sPityStart\x12\x1e\n" +
	"\vs_pity_step\x18\x06 \x01(\x01R\tsPityStep\x12\x1c\n" +
	"\n" +
	"s_pity_end\x18\a \x01(\x05R\bsPityEnd\x12\x1d\n" +
	"\n" +
	"limit_pity\x18\b \x01(\x05R\tlimitPity\x12)\n" +
	"\x11limit_rate_when_s\x18\t \x01(\x01R\x0elimitRateWhenS\x124\n" +
	"\x16max_limited_characters\x18\n" +
	" \x01(\x05R\x14maxLimitedCharacters\"\x88\x01\n" +
	"\fConfigUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12+\n" +
	"\x12updated_at_unix_ms\x18\x02 \x01(\x03R\x0fupdatedAtUnixMs\x121\n" +
	"\x06config\x18\x03 \x01(\v2\x19.configsync.v1.PoolConfigR\x06config2j\n" +
	"\x11ConfigSyncService\x12U\n" +
	"\x13SubscribePoolConfig\x12\x1f.configsync.v1.SubscribeRequest\x1a\x1b.configsync.v1.ConfigUpdate0\x01B,Z*zmd-gacha/internal/shared/pb/config;configb\x06proto3"

var (
	file_proto_config_proto_rawDescOnce sync.Once
	file_proto_config_proto_rawDescData []byte
)

func file_proto_config_proto_rawDescGZIP() []byte {
	file_proto_config_proto_rawDescOnce.Do(func() {
		file_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)))
	})
	return file_proto_config_proto_rawDescData
}

var file_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_config_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: configsync.v1.SubscribeRequest
	(*PoolConfig)(nil),       // 1: configsync.v1.PoolConfig
	(*ConfigUpdate)(nil),     // 2: configsync.v1.ConfigUpdate
}
var file_proto_config_proto_depIdxs = []int32{
	1, // 0: configsync.v1.ConfigUpdate.config:type_name -> configsync.v1.PoolConfig
	0, // 1: configsync.v1.ConfigSyncService.SubscribePoolConfig:input_type -> configsync.v1.SubscribeRequest
	2, // 2: configsync.v1.ConfigSyncService.SubscribePoolConfig:output_type -> configsync.v1.ConfigUpdate
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_config_proto_init() }
func file_proto_config_proto_init() {
	if File_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_proto_rawDesc), len(file_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_proto_goTypes,
		DependencyIndexes: file_proto_config_proto_depIdxs,
		MessageInfos:      file_proto_config_proto_msgTypes,
	}.Build()
	File_proto_config_proto = out.File
	file_proto_config_proto_goTypes = nil
	file_proto_config_proto_depIdxs = nil
}
