// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/config.proto

package config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigSyncService_SubscribePoolConfig_FullMethodName = "/configsync.v1.ConfigSyncService/SubscribePoolConfig"
)

// ConfigSyncServiceClient is the client API for ConfigSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigSyncServiceClient interface {
	// 服务端流：客户端发一次订阅请求，服务端持续推送变更
	SubscribePoolConfig(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error)
}

type configSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigSyncServiceClient(cc grpc.ClientConnInterface) ConfigSyncServiceClient {
	return &configSyncServiceClient{cc}
}

func (c *configSyncServiceClient) SubscribePoolConfig(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigSyncService_ServiceDesc.Streams[0], ConfigSyncService_SubscribePoolConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ConfigUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSyncService_SubscribePoolConfigClient = grpc.ServerStreamingClient[ConfigUpdate]

// ConfigSyncServiceServer is the server API for ConfigSyncService service.
// All implementations must embed UnimplementedConfigSyncServiceServer
// for forward compatibility.
type ConfigSyncServiceServer interface {
	// 服务端流：客户端发一次订阅请求，服务端持续推送变更
	SubscribePoolConfig(*SubscribeRequest, grpc.ServerStreamingServer[ConfigUpdate]) error
	mustEmbedUnimplementedConfigSyncServiceServer()
}

// UnimplementedConfigSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigSyncServiceServer struct{}

func (UnimplementedConfigSyncServiceServer) SubscribePoolConfig(*SubscribeRequest, grpc.ServerStreamingServer[ConfigUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribePoolConfig not implemented")
}
func (UnimplementedConfigSyncServiceServer) mustEmbedUnimplementedConfigSyncServiceServer() {}
func (UnimplementedConfigSyncServiceServer) testEmbeddedByValue()                           {}

// UnsafeConfigSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigSyncServiceServer will
// result in compilation errors.
type UnsafeConfigSyncServiceServer interface {
	mustEmbedUnimplementedConfigSyncServiceServer()
}

func RegisterConfigSyncServiceServer(s grpc.ServiceRegistrar, srv ConfigSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigSyncService_ServiceDesc, srv)
}

func _ConfigSyncService_SubscribePoolConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigSyncServiceServer).SubscribePoolConfig(m, &grpc.GenericServerStream[SubscribeRequest, ConfigUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSyncService_SubscribePoolConfigServer = grpc.ServerStreamingServer[ConfigUpdate]

// ConfigSyncService_ServiceDesc is the grpc.ServiceDesc for ConfigSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configsync.v1.ConfigSyncService",
	HandlerType: (*ConfigSyncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePoolConfig",
			Handler:       _ConfigSyncService_SubscribePoolConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/config.proto",
}
